<a href="https://colab.research.google.com/github/HeekyungKim6424/exa_machine-learning/blob/main/distingush_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#라이브러리 사용

import tensorflow as tf
import pandas as pd

In [3]:
#데이터 준비하기

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
#원핫인코딩
아이리스 = pd.get_dummies(아이리스)

#원핫인코딩은 변수가 범주형 함수일때 사용하는 코드라고 한다.
#조금 더 찾아보니 (사실 내용은 거기서 거기였음..) 숫자가 아닌objec 형의 데이터들이 있다면
#먼저 수치형으로 데이터를 변환 해주고
#다시 수치화된 데이터를 가변수화 시킨다고 한다.
#왜 굳이 다시 가변수화 시키는거야?? 생각한다면 수치화시킨채로 데이터를 냅두면 서로 관계성이 생겨버린다.
#예를들어 빨강을 1로 하고 노랑을 2로 하면 1+2=3 이렇게 관계성이 존재하게 된다.

#get_dummies 함수를 사용하면 결측값을 제외하고 0과 1로 구성된 더미값들이 만들어진다.

In [5]:
#종속변수, 독립변수 

print(아이리스.columns)
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
(150, 4) (150, 3)


In [8]:
#모델의 구조 만들기

X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X) 
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

#categorial_crosssentropy에 대해
#강사분께서 저게 뭘 의미하는지 보다 케이스에 때라 로스 값을 달리 적용하는것만 알면 된다고 하셨는데
#나는 한번 의문이 생기면 해결이 되야 직성이 풀리는 타입이라 찾아봤다.
#categorial_crosssentropy는 다중분류 손실함수라고 하는데 아마 핫인코딩 클래스에서만 사용이 가능한것 같다.

#metrics='accuracy'
#metrics는 모델의 성능을 평가하는 측정함수를 담는 변수다.
#여기선 아마 정확한값을 성능으로 평가하는거겠지?

In [9]:
#Dense 함수에 들어가는 요소들은 다음과 같다.

# 첫번째 인자: 출력 뉴런의 수를 설정
# input_dim : 입력 뉴런의 수를 설정합니다.
# init:가중치 초기화 방법을 설정(uniform은 균일분포, normal은 가우시안 분포)
# activation:활성화 함수 설정 
# linear 은 디폴트 값, 입력뉴런과 가중치로 계산된 결과값이 그대로 출력으로 나옵니다.
# relu, rectifier은 함수 은닉층에 주로 쓰입니다.

# sigmoid 시그모이드 함수, 이진 분류 문제에서 출력층에 주로 쓰입니다.
# softmax 소프트 맥스 함수, 다중 클래스 분류 문제에서 출력층에 주로 쓰입니다.
# softmax는 분류 예측을 도와주는 함수다. 분류 예측은 어떤 확률을 0~100%까지 숫자로 예측 하는것

In [10]:
#데이터로 모델 학습하기

model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1669 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1663 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1662 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1664 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1656 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1656 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1658 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1656 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1658 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1653 - accuracy: 0.9733


In [13]:
#모델 이용하기

#맨마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[4.6019400e-07 9.7699463e-02 9.0230006e-01]
 [1.1699966e-06 1.4076304e-01 8.5923576e-01]
 [1.9581462e-06 2.2500677e-01 7.7499127e-01]
 [3.5224616e-07 1.4740717e-01 8.5259247e-01]
 [3.7763182e-06 3.4551793e-01 6.5447831e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [14]:
#weights& bias 출력
print(model.get_weights())

#퍼셉트론 식에서 붙는 w값과 b값을 출력하는 코드
#퍼셉트론 식은 y=w1x1+w2x2+w3x3+b 이런 꼴이다.

[array([[ 1.6352049 ,  0.43566033,  0.08688009],
       [ 2.4008212 ,  0.70605314, -1.4155313 ],
       [-4.089864  , -0.30608985,  0.7252884 ],
       [-4.2722144 , -1.4262813 ,  2.094005  ]], dtype=float32), array([ 1.9436191,  1.1093602, -1.4258335], dtype=float32)]
