<a href="https://colab.research.google.com/github/HeekyungKim6424/exa_machine-learning/blob/main/hidden_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#히든레이어 

#히든레이어에 대해 찾아봤는데 입력층과 출력층 사이의 층이라고만 나와있지 왜 이게 오류를 줄여주는지에 대해서는 찾지 못했다
#아마 내가 구글링 실력이 부족해서 그런게 아닐까 조심스레 추측해본다.
#암튼 히든레이어 코드는 일전에 했었던 프로그래밍과 다른게 거의 없다.
#모델 학습시킬때 변수를 H를 하나 더 추가하는것 뿐이다.
#그럼에도 불구하고......실습을 해보도록 하겠다.

1.보스턴 집값 예측하기.hidden layer 버전

In [1]:
#라이브러리 사용

import tensorflow as tf
import pandas as pd

In [5]:
#데이터 준비
파일경로='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴=pd.read_csv(파일경로)
print(보스턴.head())

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]


In [6]:
#독립변수, 종속변수

독립=보스턴[['crim', 'zn', 'indus', 'chas', 'nox','rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속=보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [7]:
#모델 구조만들기

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X) #히든레이어에서 새로 추가된 코드!
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [8]:
#모델 구조 확인
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [10]:
#데이터로 모델 학습하기
model.fit(독립, 종속, epochs=100)

Epoch 1/100
16/16 [==============================] - 1s 1ms/step - loss: 62833.6650
Epoch 2/100
16/16 [==============================] - 0s 1ms/step - loss: 44685.7574
Epoch 3/100
16/16 [==============================] - 0s 1ms/step - loss: 34327.3398
Epoch 4/100
16/16 [==============================] - 0s 1ms/step - loss: 25747.5210
Epoch 5/100
16/16 [==============================] - 0s 1ms/step - loss: 18886.8263
Epoch 6/100
16/16 [==============================] - 0s 1ms/step - loss: 13122.5922
Epoch 7/100
16/16 [==============================] - 0s 1ms/step - loss: 8730.4846
Epoch 8/100
16/16 [==============================] - 0s 1ms/step - loss: 5300.7724
Epoch 9/100
16/16 [==============================] - 0s 1ms/step - loss: 2930.5472
Epoch 10/100
16/16 [==============================] - 0s 1ms/step - loss: 1494.5800
Epoch 11/100
16/16 [==============================] - 0s 1ms/step - loss: 643.8381
Epoch 12/100
16/16 [==============================] - 0s 1ms/step - loss: 278.43

In [11]:
#모델 이용
print(model.predict(독립[:5]))
print(종속[:5])

[[29.741642]
 [26.022701]
 [28.06738 ]
 [27.723454]
 [27.16511 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [12]:
#모델 구조 확인
print(model.get_weights())

[array([[ 0.3217333 , -0.17695138, -0.29265323,  0.45109028,  0.41662124,
        -0.47231218, -0.39724082, -0.57261384,  0.18243322,  0.1378381 ],
       [-0.387063  , -0.01333966,  0.01394937, -0.22023943,  0.28661564,
        -0.21580762, -0.3596682 ,  0.3654621 , -0.22437696,  0.10493944],
       [ 0.25663996, -0.16226934,  0.39314586, -0.37301552, -0.14394681,
         0.4617465 , -0.13058704, -0.45807123, -0.13673635,  0.15280272],
       [-0.88530624, -0.6201593 ,  0.85643095, -0.10499629,  0.31079856,
         0.21672028,  0.37679094, -0.4949744 ,  0.16508484,  1.2837104 ],
       [-0.8263838 , -0.26189995, -0.06801157, -0.05182546,  0.22777101,
        -0.4426386 ,  0.09200031, -0.23766495, -0.05294191,  0.17122793],
       [-0.56079227, -0.59059906,  0.66954005, -0.39057496, -0.35564607,
        -0.1103313 ,  0.11000735, -0.67841834, -0.13839911,  1.067483  ],
       [ 0.23007186, -0.30108318, -0.13015573, -0.03554767, -0.07908184,
        -0.09470329, -0.07393911, -0.1762755

2.아이리스 품종 분류.hidden layer 버전

In [13]:
# 라이브러리 사용

import tensorflow as tf
import pandas as pd

In [14]:
# 데이터를 준비

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [15]:
# 원핫인코딩

아이리스 = pd.get_dummies(아이리스)

In [16]:
# 종속변수, 독립변수

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [17]:
# 모델 구조 만들기

X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [18]:
# 모델 구조 확인

model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [19]:
# 모델 학습.

model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 2ms/step - loss: 1.0896 - accuracy: 0.6480
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9806 - accuracy: 0.6866
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9708 - accuracy: 0.6359
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9275 - accuracy: 0.6467
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8681 - accuracy: 0.6875
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8284 - accuracy: 0.6905
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8206 - accuracy: 0.6454
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.7552 - accuracy: 0.7066
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.7292 - accuracy: 0.6693
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.7048 - accuracy: 0.6762
Epoch 11/100
5/5 [===========

In [20]:
# 모델 이용

print(model.predict(독립[:5]))
print(종속[:5])

[[9.9991345e-01 1.3113682e-07 8.6432439e-05]
 [9.9979836e-01 8.6779352e-07 2.0077778e-04]
 [9.9982065e-01 4.3664221e-07 1.7895093e-04]
 [9.9970090e-01 1.5385532e-06 2.9755093e-04]
 [9.9991226e-01 1.1456709e-07 8.7612359e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
